[build]
  command = "ng build --configuration production"
  publish = "dist/edigatech"  # <- update if your folder is named differently

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
